// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string):Promise<main.ConnectionStatus>;

export function ConnectWiFi(arg1:string,arg2:number,arg3:string):Promise<main.ConnectionStatus>;

export function Disconnect():Promise<void>;

export function GetWidgetTree():Promise<string>;

export function Lint(arg1:string):Promise<Array<main.Diagnostic>>;

export function ListDevices():Promise<Array<main.DeviceInfo>>;

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;

export function LoadWorkspaceSettings(arg1:string):Promise<main.WorkspaceSettings>;

export function PickWorkspace():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RunFile(arg1:string):Promise<Array<main.RunResult>>;

export function SaveWorkspaceSettings(arg1:string,arg2:main.WorkspaceSettings):Promise<void>;

export function StartWiFiDiscovery():Promise<void>;

export function Status():Promise<main.ConnectionStatus>;

export function StopWiFiDiscovery():Promise<void>;

export function TakeScreenshot():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
