// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectWiFi(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectWiFi'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetWidgetTree() {
  return window['go']['main']['App']['GetWidgetTree']();
}

export function Lint(arg1) {
  return window['go']['main']['App']['Lint'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function LoadWorkspaceSettings(arg1) {
  return window['go']['main']['App']['LoadWorkspaceSettings'](arg1);
}

export function PickWorkspace() {
  return window['go']['main']['App']['PickWorkspace']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunFile(arg1) {
  return window['go']['main']['App']['RunFile'](arg1);
}

export function SaveWorkspaceSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkspaceSettings'](arg1, arg2);
}

export function StartWiFiDiscovery() {
  return window['go']['main']['App']['StartWiFiDiscovery']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopWiFiDiscovery() {
  return window['go']['main']['App']['StopWiFiDiscovery']();
}

export function TakeScreenshot() {
  return window['go']['main']['App']['TakeScreenshot']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
