/// Converts `DartObject` constant values from `flutter_probe_annotation`
/// types into ProbeScript text.
///
/// The emitter is a `StringBuffer` builder; the public API is `emitHeader`,
/// `emitSuite`, `emitTest`, `emitRecipe`, plus the `isEmpty` getter and
/// `toString()`. Indentation is tracked per nested block (if / repeat / mock).
library;

import 'package:analyzer/dart/constant/value.dart';

/// Returns the simple class name of a constant value's type. Works across
/// the analyzer 7→8+ element-model migration — uses `getDisplayString()`
/// rather than the deprecated `type.element?.name` accessor.
String _typeNameOf(DartObject value) {
  final type = value.type;
  if (type == null) return '';
  final repr = type.getDisplayString();
  final lt = repr.indexOf('<');
  final base = lt < 0 ? repr : repr.substring(0, lt);
  return base.replaceAll('*', '').replaceAll('?', '');
}

class ProbeEmitter {
  final StringBuffer _buf = StringBuffer();
  bool _hasContent = false;

  bool get isEmpty => !_hasContent;

  @override
  String toString() => _buf.toString();

  // ---- Top-level emitters ----

  void emitHeader(String sourcePath) {
    _buf.writeln('# Generated by flutter_probe_gen — do not edit by hand.');
    _buf.writeln('# Source: $sourcePath');
    _buf.writeln();
  }

  void emitSuite(DartObject suite) {
    final beforeAll = _stepList(suite, 'beforeAll');
    final beforeEach = _stepList(suite, 'beforeEach');
    final afterEach = _stepList(suite, 'afterEach');
    final afterAll = _stepList(suite, 'afterAll');
    final onFailure = _stepList(suite, 'onFailure');
    final recipes = _objList(suite, 'recipes');
    final tests = _objList(suite, 'tests');

    for (final r in recipes) {
      emitRecipe(r);
    }
    if (beforeAll.isNotEmpty) {
      _emitHook('before all tests', beforeAll);
    }
    if (beforeEach.isNotEmpty) {
      _emitHook('before each test', beforeEach);
    }
    if (afterEach.isNotEmpty) {
      _emitHook('after each test', afterEach);
    }
    if (afterAll.isNotEmpty) {
      _emitHook('after all tests', afterAll);
    }
    if (onFailure.isNotEmpty) {
      _emitHook('on failure', onFailure);
    }
    for (final t in tests) {
      emitTest(t);
    }
  }

  void emitTest(DartObject test) {
    final name = _str(test, 'name') ?? 'unnamed';
    final tags = _strList(test, 'tags');
    final steps = _stepList(test, 'steps');
    final examples = test.getField('examples');

    _buf.writeln('test "${_escape(name)}"');
    if (tags.isNotEmpty) {
      _buf.writeln('  ${tags.map((t) => '@$t').join(' ')}');
    }
    for (final s in steps) {
      _emitStep(s, 1);
    }
    if (examples != null && !examples.isNull) {
      _emitExamples(examples);
    }
    _buf.writeln();
    _hasContent = true;
  }

  void emitRecipe(DartObject recipe) {
    final name = _str(recipe, 'name') ?? 'unnamed';
    final params = _strList(recipe, 'params');
    final steps = _stepList(recipe, 'steps');
    final paramSig = params.isEmpty ? '' : ' (${params.join(', ')})';
    _buf.writeln('recipe "${_escape(name)}"$paramSig');
    for (final s in steps) {
      _emitStep(s, 1);
    }
    _buf.writeln();
    _hasContent = true;
  }

  void _emitHook(String header, List<DartObject> steps) {
    _buf.writeln(header);
    for (final s in steps) {
      _emitStep(s, 1);
    }
    _buf.writeln();
    _hasContent = true;
  }

  /// Emits a `composite test "name"` block from a `@ProbeCompositeTest`
  /// annotation. Devices declaration, then a body of `<alias>:` blocks
  /// (rendered from [OnDevice] entries) and `sync "label"` lines
  /// (rendered from [Sync] entries).
  void emitCompositeTest(DartObject composite) {
    final name = _str(composite, 'name') ?? 'unnamed';
    final tags = _strList(composite, 'tags');
    final devices = _objList(composite, 'devices');
    final body = _objList(composite, 'body');

    _buf.writeln('composite test "${_escape(name)}"');
    if (tags.isNotEmpty) {
      _buf.writeln('  ${tags.map((t) => '@$t').join(' ')}');
    }
    if (devices.isNotEmpty) {
      _buf.writeln('  devices');
      for (final d in devices) {
        final alias = _str(d, 'alias') ?? '';
        final target = _str(d, 'target') ?? '';
        if (target.isEmpty) {
          _buf.writeln('    $alias:');
        } else {
          _buf.writeln('    $alias: $target');
        }
      }
    }
    for (final element in body) {
      final t = _typeNameOf(element);
      if (t == 'OnDevice') {
        final alias = _str(element, 'alias') ?? '';
        final steps = _objList(element, 'steps');
        if (alias.isEmpty || steps.isEmpty) continue;
        _buf.writeln('  $alias:');
        for (final s in steps) {
          _emitStep(s, 2);
        }
      } else if (t == 'Sync') {
        final label = _str(element, 'label') ?? '';
        _buf.writeln('  sync "${_escape(label)}"');
      }
      // Other Step types in a composite body are ignored — DSL doc says
      // body must contain only OnDevice and Sync.
    }
    _buf.writeln();
    _hasContent = true;
  }

  // ---- Step dispatch ----

  void _emitStep(DartObject step, int depth) {
    final indent = '  ' * depth;
    final type = _typeNameOf(step);
    switch (type) {
      // App lifecycle
      case 'Open':
        _buf.writeln('${indent}open the app');
        break;
      case 'OpenLink':
        _buf.writeln('${indent}open link "${_escape(_str(step, 'url') ?? '')}"');
        break;
      case 'Close':
        _buf.writeln('${indent}close the app');
        break;
      case 'Restart':
        _buf.writeln('${indent}restart the app');
        break;
      case 'Kill':
        _buf.writeln('${indent}kill the app');
        break;
      case 'ClearAppData':
        _buf.writeln('${indent}clear app data');
        break;

      // Tap-family
      case 'Tap':
        _emitTapLike(step, depth, 'tap', supportsIfVisible: true);
        break;
      case 'DoubleTap':
        _emitTapLike(step, depth, 'double tap');
        break;
      case 'LongPress':
        _emitTapLike(step, depth, 'long press');
        break;
      case 'Press':
        _buf.writeln('${indent}press ${_str(step, 'key') ?? 'home'}');
        break;
      case 'GoBack':
        _buf.writeln('${indent}go back');
        break;

      // Text input
      case 'Type':
        final text = _str(step, 'text') ?? '';
        final into = step.getField('into');
        final ifVisible = _bool(step, 'ifVisible');
        final intoStr = (into == null || into.isNull)
            ? ''
            : ' into ${_renderSelector(into)}';
        final visStr = ifVisible ? ' if visible' : '';
        _buf.writeln('${indent}type "${_escape(text)}"$intoStr$visStr');
        break;
      case 'Clear':
        _buf.writeln('${indent}clear ${_renderTargetFromTap(step)}');
        break;

      // Scroll/swipe/drag
      case 'Swipe':
        _emitMotion(step, depth, 'swipe');
        break;
      case 'Scroll':
        _emitMotion(step, depth, 'scroll');
        break;
      case 'Drag':
        final from = step.getField('from');
        final to = step.getField('to');
        _buf.writeln('${indent}drag ${_renderSelector(from!)} to ${_renderSelector(to!)}');
        break;
      case 'Pinch':
        final zoomIn = _bool(step, 'zoomIn');
        _buf.writeln('${indent}pinch ${zoomIn ? 'out' : 'in'}');
        break;
      case 'Rotate':
        final orientation = _str(step, 'orientation') ?? 'portrait';
        _buf.writeln('${indent}rotate $orientation');
        break;
      case 'Toggle':
        _buf.writeln('${indent}toggle "${_escape(_str(step, 'name') ?? '')}"');
        break;
      case 'Shake':
        _buf.writeln('${indent}shake');
        break;

      // Permissions
      case 'AllowPermission':
        _buf.writeln('${indent}allow permission "${_escape(_str(step, 'name') ?? '')}"');
        break;
      case 'DenyPermission':
        _buf.writeln('${indent}deny permission "${_escape(_str(step, 'name') ?? '')}"');
        break;
      case 'GrantAllPermissions':
        _buf.writeln('${indent}grant all permissions');
        break;
      case 'RevokeAllPermissions':
        _buf.writeln('${indent}revoke all permissions');
        break;

      // Clipboard / device control
      case 'CopyToClipboard':
        _buf.writeln('${indent}copy "${_escape(_str(step, 'text') ?? '')}" to clipboard');
        break;
      case 'PasteFromClipboard':
        _buf.writeln('${indent}paste from clipboard');
        break;
      case 'SetLocation':
        final lat = _double(step, 'lat');
        final lng = _double(step, 'lng');
        _buf.writeln('${indent}set location $lat, $lng');
        break;
      case 'VerifyExternalBrowser':
        _buf.writeln('${indent}verify external browser opened');
        break;

      // Biometric (Face ID / Touch ID / fingerprint) — simulator/emulator only
      case 'EnrollBiometric':
        _buf.writeln('${indent}enroll biometric');
        break;
      case 'BiometricMatch':
        _buf.writeln('${indent}biometric match');
        break;
      case 'BiometricNoMatch':
        _buf.writeln('${indent}biometric no match');
        break;

      // Diagnostics
      case 'TakeScreenshot':
        _buf.writeln('${indent}take screenshot "${_escape(_str(step, 'name') ?? '')}"');
        break;
      case 'CompareScreenshot':
        _buf.writeln('${indent}compare screenshot "${_escape(_str(step, 'name') ?? '')}"');
        break;
      case 'DumpWidgetTree':
        _buf.writeln('${indent}dump widget tree');
        break;
      case 'SaveLogs':
        _buf.writeln('${indent}save logs');
        break;
      case 'Pause':
        _buf.writeln('${indent}pause');
        break;
      case 'Log':
        _buf.writeln('${indent}log "${_escape(_str(step, 'message') ?? '')}"');
        break;

      // Variables
      case 'Store':
        final value = _str(step, 'value') ?? '';
        final as = _str(step, 'as') ?? '';
        _buf.writeln('${indent}store "${_escape(value)}" as $as');
        break;

      // Assertions
      case 'See':
        _emitSee(step, depth);
        break;
      case 'DontSee':
        _emitSee(step, depth, negated: true);
        break;

      // Wait
      case 'WaitFor':
        _buf.writeln('${indent}wait ${_double(step, 'seconds')} seconds');
        break;
      case 'WaitForPageLoad':
        _buf.writeln('${indent}wait for the page to load');
        break;
      case 'WaitForNetworkIdle':
        _buf.writeln('${indent}wait until network is idle');
        break;
      case 'WaitForAnimations':
        _buf.writeln('${indent}wait for animations to end');
        break;
      case 'WaitUntil':
        final target = _str(step, 'target') ?? '';
        final appears = _bool(step, 'appears');
        final byId = _bool(step, 'byId');
        // byId factories emit unquoted #key so the Go parser's WaitSelector
        // branch (parser.go:846) matches; text factories emit quoted form
        // for the WaitAppears/WaitDisappears branch.
        final rendered = byId ? '#$target' : '"${_escape(target)}"';
        _buf.writeln('${indent}wait until $rendered '
            '${appears ? 'appears' : 'disappears'}');
        break;

      // Control flow
      case 'If':
        final cond = _str(step, 'condition') ?? '';
        final thenBody = _stepList(step, 'then');
        final elseBody = _stepList(step, 'otherwise');
        _buf.writeln('${indent}if "${_escape(cond)}" appears');
        for (final s in thenBody) {
          _emitStep(s, depth + 1);
        }
        if (elseBody.isNotEmpty) {
          _buf.writeln('${indent}otherwise');
          for (final s in elseBody) {
            _emitStep(s, depth + 1);
          }
        }
        break;
      case 'Repeat':
        final times = _int(step, 'times');
        final body = _stepList(step, 'body');
        _buf.writeln('${indent}repeat $times times');
        for (final s in body) {
          _emitStep(s, depth + 1);
        }
        break;

      // Dart escape hatch
      case 'RunDart':
        final code = _str(step, 'code') ?? '';
        _buf.writeln('${indent}run dart:');
        for (final line in code.split('\n')) {
          _buf.writeln('${'  ' * (depth + 1)}$line');
        }
        break;

      // HTTP
      case 'Mock':
        final method = _httpMethod(step, 'method');
        final path = _str(step, 'path') ?? '';
        final status = _int(step, 'status');
        final body = _str(step, 'body') ?? '';
        // Path must be quoted so the lexer doesn't split on `/` and lose
        // segments after the first IDENT. Parser test fixture at
        // internal/parser/parser_test.go shows quoted form is canonical.
        _buf.writeln(
            '${indent}when the app calls $method "${_escape(path)}"');
        if (body.isNotEmpty) {
          _buf.writeln(
              '${'  ' * (depth + 1)}respond with $status and body "${_escape(body)}"');
        } else {
          _buf.writeln('${'  ' * (depth + 1)}respond with $status');
        }
        break;
      case 'CallHttp':
        final method = _httpMethod(step, 'method');
        final url = _str(step, 'url') ?? '';
        final body = _str(step, 'body');
        if (body == null || body.isEmpty) {
          _buf.writeln('${indent}call $method "${_escape(url)}"');
        } else {
          _buf.writeln(
              '${indent}call $method "${_escape(url)}" with body "${_escape(body)}"');
        }
        break;

      // Recipe invocation
      case 'RecipeStep':
        final name = _str(step, 'name') ?? '';
        final args = _strList(step, 'args');
        final argStr = args.map((a) => '"${_escape(a)}"').join(' ');
        _buf.writeln('$indent$name${argStr.isEmpty ? '' : ' $argStr'}');
        break;

      default:
        // Unknown step — emit as a line comment so the file still parses.
        _buf.writeln('$indent# unknown step: $type');
    }
  }

  // ---- Specialized emitters ----

  void _emitTapLike(DartObject step, int depth, String verb,
      {bool supportsIfVisible = false}) {
    final indent = '  ' * depth;
    final target = _renderTargetFromTap(step);
    final ifVis =
        supportsIfVisible && _bool(step, 'ifVisible') ? ' if visible' : '';
    _buf.writeln('$indent$verb $target$ifVis');
  }

  String _renderTargetFromTap(DartObject step) {
    final selector = step.getField('selector');
    if (selector != null && !selector.isNull) return _renderSelector(selector);
    final id = _str(step, 'id');
    if (id != null) return '#$id';
    final text = _str(step, 'text');
    if (text != null) return '"${_escape(text)}"';
    return '"<unknown>"';
  }

  void _emitMotion(DartObject step, int depth, String verb) {
    final indent = '  ' * depth;
    final dirStr = _direction(step.getField('direction'));
    final on = step.getField('on');
    final tail = (on == null || on.isNull) ? '' : ' ${_renderSelector(on)}';
    _buf.writeln('$indent$verb $dirStr$tail');
  }

  void _emitSee(DartObject step, int depth, {bool negated = false}) {
    final indent = '  ' * depth;
    final exactly = step.getField('exactly');

    // Target: text, id, or rich selector. Mirror the same priority order
    // used by the tap-family target resolver.
    final selector = step.getField('selector');
    final id = _str(step, 'id');
    final text = _str(step, 'text');
    String target;
    if (selector != null && !selector.isNull) {
      target = _renderSelector(selector);
    } else if (id != null && id.isNotEmpty) {
      target = '#$id';
    } else {
      target = '"${_escape(text ?? '')}"';
    }

    final containing = _str(step, 'containing');
    final matching = _str(step, 'matching');
    final stateName = _seeStateName(step.getField('state'));

    final countStr = (exactly == null || exactly.isNull)
        ? ''
        : 'exactly ${exactly.toIntValue()} ';
    final verb = negated ? "don't see" : 'see';

    // Compose suffixes additively — state, contains, and matching can ALL
    // appear in a single assertion. The Go parser at parser.go:728-769
    // parses them sequentially after the selector, so we emit in the same
    // canonical order: <state> contains <X> matching <Y>.
    final parts = <String>['$verb $countStr$target'.replaceAll('  ', ' ')];
    if (stateName != null) parts.add('is $stateName');
    if (containing != null && containing.isNotEmpty) {
      parts.add('contains "${_escape(containing)}"');
    }
    if (matching != null && matching.isNotEmpty) {
      parts.add('matching "${_escape(matching)}"');
    }
    _buf.writeln('$indent${parts.join(' ')}');
  }

  /// Maps a SeeState enum DartObject to its parser keyword, or null if
  /// SeeState.none. Reads the enum constant identifier rather than trusting
  /// the index so reordering the enum doesn't silently corrupt output.
  String? _seeStateName(DartObject? stateField) {
    if (stateField == null || stateField.isNull) return null;
    final name = _enumName(stateField);
    // Map DSL enum name → parser keyword. 'none' means no state suffix.
    const valid = {'enabled', 'disabled', 'checked', 'focused'};
    return valid.contains(name) ? name : null;
  }

  void _emitExamples(DartObject examples) {
    final source = _str(examples, 'source');
    if (source != null && source.isNotEmpty) {
      _buf.writeln('  with examples from "${_escape(source)}"');
      return;
    }
    final headers = _strList(examples, 'headers');
    final rowsRaw = examples.getField('rows')?.toListValue() ?? [];
    if (headers.isEmpty || rowsRaw.isEmpty) return;
    _buf.writeln('  with examples:');
    _buf.writeln('    | ${headers.join(' | ')} |');
    for (final row in rowsRaw) {
      final cells = (row.toListValue() ?? [])
          .map((c) => c.toStringValue() ?? '')
          .toList();
      _buf.writeln('    | ${cells.join(' | ')} |');
    }
  }

  // ---- Selectors ----

  String _renderSelector(DartObject sel) {
    final type = _typeNameOf(sel);
    switch (type) {
      case 'TextSel':
        return '"${_escape(_str(sel, 'value') ?? '')}"';
      case 'IdSel':
        return '#${_str(sel, 'key') ?? ''}';
      case 'TypeSel':
        return _str(sel, 'widgetType') ?? '';
      case 'Field':
        final id = _str(sel, 'id');
        if (id != null) return '#$id';
        final text = _str(sel, 'text');
        if (text != null) return '"${_escape(text)}"';
        return '"<field>"';
      case 'Ordinal':
        final n = _int(sel, 'n');
        final text = _str(sel, 'text') ?? '';
        final container = _str(sel, 'container');
        final base = '${_ordinal(n)} "${_escape(text)}"';
        return container == null
            ? base
            : '$base in "${_escape(container)}"';
      case 'Below':
      case 'Above':
        final target = _str(sel, 'target') ?? '';
        final anchor = _str(sel, 'anchor') ?? '';
        final word = type.toLowerCase();
        return '"${_escape(target)}" $word "${_escape(anchor)}"';
      case 'LeftOf':
        final t = _str(sel, 'target') ?? '';
        final a = _str(sel, 'anchor') ?? '';
        return '"${_escape(t)}" left of "${_escape(a)}"';
      case 'RightOf':
        final t = _str(sel, 'target') ?? '';
        final a = _str(sel, 'anchor') ?? '';
        return '"${_escape(t)}" right of "${_escape(a)}"';
      case 'InContainer':
        final t = _str(sel, 'text') ?? '';
        final c = _str(sel, 'container') ?? '';
        return '"${_escape(t)}" in "${_escape(c)}"';
      default:
        return '"<unknown selector>"';
    }
  }

  // ---- DartObject helpers ----

  String? _str(DartObject obj, String field) =>
      obj.getField(field)?.toStringValue();

  bool _bool(DartObject obj, String field) =>
      obj.getField(field)?.toBoolValue() ?? false;

  int _int(DartObject obj, String field) =>
      obj.getField(field)?.toIntValue() ?? 0;

  num _double(DartObject obj, String field) {
    final f = obj.getField(field);
    if (f == null) return 0;
    final d = f.toDoubleValue();
    if (d != null) return d;
    return f.toIntValue() ?? 0;
  }

  List<String> _strList(DartObject obj, String field) {
    final list = obj.getField(field)?.toListValue();
    if (list == null) return const [];
    return list.map((e) => e.toStringValue() ?? '').toList();
  }

  List<DartObject> _stepList(DartObject obj, String field) =>
      _objList(obj, field);

  List<DartObject> _objList(DartObject obj, String field) {
    final list = obj.getField(field)?.toListValue();
    if (list == null) return const [];
    return list;
  }

  String _httpMethod(DartObject obj, String field) {
    final name = _enumName(obj.getField(field));
    // HttpMethod enum: get | post | put | delete → uppercase.
    if (name == null || name.isEmpty) return 'GET';
    return name.toUpperCase();
  }

  String _direction(DartObject? d) {
    if (d == null) return 'down';
    final name = _enumName(d);
    // Direction enum names map 1:1 to ProbeScript keywords.
    if (name == null || name.isEmpty) return 'down';
    return name;
  }

  /// Returns the Dart enum constant identifier (e.g. "up" for Direction.up).
  /// Works on Dart 2.15+ where every enum value has an auto-generated `_name`
  /// field. Decouples emitter correctness from enum *declaration order* —
  /// reordering a DSL enum no longer silently corrupts emitted ProbeScript.
  String? _enumName(DartObject? value) {
    if (value == null || value.isNull) return null;
    final n = value.getField('_name')?.toStringValue();
    if (n != null) return n;
    // Older Dart versions exposed the name via `name`; try that next.
    return value.getField('name')?.toStringValue();
  }

  String _ordinal(int n) {
    if (n == 1) return '1st';
    if (n == 2) return '2nd';
    if (n == 3) return '3rd';
    return '${n}th';
  }

  String _escape(String s) =>
      s.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
}
