package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

const (
	defaultModel  = "claude-sonnet-4-20250514"
	defaultAPIURL = "https://api.anthropic.com/v1/messages"
	apiVersion    = "2023-06-01"
	maxTokens     = 4096
)

// Generator calls the Claude API for LLM-powered test generation and
// self-healing selector suggestions.
type Generator struct {
	APIKey  string
	Model   string
	BaseURL string
	Client  *http.Client
}

// GenerateRequest describes what to generate.
type GenerateRequest struct {
	Prompt     string   // natural-language description of the test
	WidgetTree string   // optional: current widget tree dump (JSON)
	Recipes    []string // optional: existing recipe names for context
	AppName    string
	Platform   string
}

// GenerateResult is the output of a generation call.
type GenerateResult struct {
	ProbeScript string
	Filename    string
	Description string
}

// NewGenerator creates a Generator with sensible defaults.
func NewGenerator(apiKey, model string) *Generator {
	if model == "" {
		model = defaultModel
	}
	return &Generator{
		APIKey:  apiKey,
		Model:   model,
		BaseURL: defaultAPIURL,
		Client: &http.Client{
			Timeout: 120 * time.Second,
		},
	}
}

// probeScriptSystemPrompt provides full ProbeScript syntax to the LLM.
const probeScriptSystemPrompt = `You are an expert at writing FlutterProbe tests in ProbeScript syntax.

ProbeScript uses natural English with indent-based blocks (like Python). Key rules:
- Tests start with: test "test name"
- All steps inside a test are indented by 2 spaces
- Tags go on the line after test declaration: @smoke @critical
- Available commands:
  - open the app
  - tap on "Text" / tap #key_id / tap on the 1st "Item"
  - type "value" into the "Label" field / type "value" into #key_id
  - see "Text" — assert text is visible
  - wait until "Text" appears — wait with timeout
  - wait N seconds
  - wait for the page to load
  - swipe up / swipe down / swipe left / swipe right
  - scroll down / scroll up
  - go back
  - take a screenshot "name"
  - clear app data
  - restart the app
  - allow permission "camera" / deny permission "notifications"
  - grant all permissions / revoke all permissions
  - if "Text" is visible / else
  - repeat N times
  - long press on "Text"
  - don't see "Text" — assert text is NOT visible
  - run dart: (followed by indented Dart code block)

Selector types:
  - "Text" — match by visible text
  - #key_id — match by ValueKey
  - "text" in "Container" — positional (text inside a parent)
  - 1st "Item" / 2nd "Item" — ordinal

Recipes (reusable step sequences):
  recipe "name" (param1, param2)
    step using <param1>

Use statements import recipes:
  use "path/to/recipes.probe"

Hooks:
  before each
    step
  after each
    step
  on failure
    take a screenshot "failure"

Data-driven tests:
  test "login with <email>"
    type <email> into the "Email" field
    Examples:
      | email            |
      | user@test.com    |
      | admin@test.com   |

IMPORTANT: Output ONLY the ProbeScript content. Do not wrap in markdown code blocks.
Include a comment at the top: # Generated by FlutterProbe AI`

// Generate calls the Claude API to produce a ProbeScript test from a prompt.
func (g *Generator) Generate(ctx context.Context, req GenerateRequest) (*GenerateResult, error) {
	if g.APIKey == "" {
		return nil, fmt.Errorf("ai: API key is required (set --api-key or ai.api_key in probe.yaml)")
	}

	userMsg := buildGeneratePrompt(req)

	body, err := g.callAPI(ctx, probeScriptSystemPrompt, userMsg)
	if err != nil {
		return nil, fmt.Errorf("ai generate: %w", err)
	}

	script := extractProbeScript(body)
	filename := inferFilename(req.Prompt)
	desc := inferDescription(req.Prompt)

	return &GenerateResult{
		ProbeScript: script,
		Filename:    filename,
		Description: desc,
	}, nil
}

// SuggestSelector asks the LLM for a replacement selector given a failed
// selector and the current widget tree.
func (g *Generator) SuggestSelector(ctx context.Context, failed string, widgetTree string) (string, error) {
	if g.APIKey == "" {
		return "", fmt.Errorf("ai: API key is required")
	}

	system := `You are a FlutterProbe selector expert. Given a failed selector and the current widget tree, suggest the best replacement selector.

Selector types:
- "Text" — match by visible text
- #key_id — match by ValueKey
- "text" in "Container" — positional
- 1st "Item" — ordinal

Reply with ONLY the replacement selector on a single line. No explanation.`

	user := fmt.Sprintf("Failed selector: %s\n\nCurrent widget tree:\n%s", failed, widgetTree)

	body, err := g.callAPI(ctx, system, user)
	if err != nil {
		return "", fmt.Errorf("ai suggest selector: %w", err)
	}

	return strings.TrimSpace(body), nil
}

// ---- Claude API plumbing ----

type apiRequest struct {
	Model     string       `json:"model"`
	MaxTokens int          `json:"max_tokens"`
	System    string       `json:"system,omitempty"`
	Messages  []apiMessage `json:"messages"`
}

type apiMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type apiResponse struct {
	Content []struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"content"`
	Error *struct {
		Type    string `json:"type"`
		Message string `json:"message"`
	} `json:"error"`
	Usage struct {
		InputTokens  int `json:"input_tokens"`
		OutputTokens int `json:"output_tokens"`
	} `json:"usage"`
}

// callAPI sends a single-turn request to the Claude messages API.
func (g *Generator) callAPI(ctx context.Context, system, userMsg string) (string, error) {
	reqBody := apiRequest{
		Model:     g.Model,
		MaxTokens: maxTokens,
		System:    system,
		Messages: []apiMessage{
			{Role: "user", Content: userMsg},
		},
	}

	payload, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}

	url := g.BaseURL
	if url == "" {
		url = defaultAPIURL
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(payload))
	if err != nil {
		return "", err
	}
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("x-api-key", g.APIKey)
	httpReq.Header.Set("anthropic-version", apiVersion)

	resp, err := g.Client.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("API request failed: %w", err)
	}
	defer resp.Body.Close()

	respBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("reading API response: %w", err)
	}

	if resp.StatusCode == 429 {
		return "", fmt.Errorf("API rate limited (429) — try again shortly")
	}
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("API returned %d: %s", resp.StatusCode, string(respBytes))
	}

	var apiResp apiResponse
	if err := json.Unmarshal(respBytes, &apiResp); err != nil {
		return "", fmt.Errorf("parsing API response: %w", err)
	}

	if apiResp.Error != nil {
		return "", fmt.Errorf("API error (%s): %s", apiResp.Error.Type, apiResp.Error.Message)
	}

	if len(apiResp.Content) == 0 {
		return "", fmt.Errorf("API returned empty content")
	}

	// Concatenate all text blocks
	var sb strings.Builder
	for _, block := range apiResp.Content {
		if block.Type == "text" {
			sb.WriteString(block.Text)
		}
	}

	return sb.String(), nil
}

// ---- Prompt building helpers ----

func buildGeneratePrompt(req GenerateRequest) string {
	var sb strings.Builder

	sb.WriteString("Generate a ProbeScript test based on this description:\n\n")
	sb.WriteString(req.Prompt)
	sb.WriteString("\n")

	if req.AppName != "" {
		sb.WriteString(fmt.Sprintf("\nApp name: %s\n", req.AppName))
	}
	if req.Platform != "" {
		sb.WriteString(fmt.Sprintf("Platform: %s\n", req.Platform))
	}

	if req.WidgetTree != "" {
		sb.WriteString("\nCurrent widget tree (use these selectors when possible):\n")
		sb.WriteString(req.WidgetTree)
		sb.WriteString("\n")
	}

	if len(req.Recipes) > 0 {
		sb.WriteString("\nAvailable recipes (you can call these by name):\n")
		for _, r := range req.Recipes {
			sb.WriteString(fmt.Sprintf("  - %s\n", r))
		}
	}

	return sb.String()
}

// extractProbeScript cleans up LLM output: strips markdown fences, trims whitespace.
func extractProbeScript(raw string) string {
	s := strings.TrimSpace(raw)

	// Strip markdown code fences if the LLM wrapped output despite instructions
	if strings.HasPrefix(s, "```") {
		lines := strings.Split(s, "\n")
		// Remove first line (```probe or ```)
		if len(lines) > 1 {
			lines = lines[1:]
		}
		// Remove last line if it's ```
		if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "```" {
			lines = lines[:len(lines)-1]
		}
		s = strings.Join(lines, "\n")
	}

	return strings.TrimSpace(s)
}

// inferFilename derives a .probe filename from the prompt.
func inferFilename(prompt string) string {
	// Take first ~40 chars, lowercase, replace spaces with underscores
	name := strings.ToLower(prompt)
	if len(name) > 40 {
		name = name[:40]
	}
	name = strings.Map(func(r rune) rune {
		if r >= 'a' && r <= 'z' || r >= '0' && r <= '9' {
			return r
		}
		if r == ' ' || r == '-' {
			return '_'
		}
		return -1
	}, name)
	// Collapse multiple underscores
	for strings.Contains(name, "__") {
		name = strings.ReplaceAll(name, "__", "_")
	}
	name = strings.Trim(name, "_")
	if name == "" {
		name = "generated_test"
	}
	return name + ".probe"
}

// inferDescription creates a short description from the prompt.
func inferDescription(prompt string) string {
	desc := prompt
	if len(desc) > 100 {
		desc = desc[:100] + "..."
	}
	return desc
}
