package ai

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// Failure is one failed test as triage sees it. Error is the runner's error
// text, which since FP-13 carries the failing line, the step and the visible
// texts/keys on screen — usually enough for a small text-only model.
type Failure struct {
	Test  string
	File  string
	Error string
}

// TriageNote is advisory text for one failure.
type TriageNote struct {
	Test   string
	Advice string
}

// TriageOptions bounds a triage pass. Zero values pick conservative defaults.
type TriageOptions struct {
	MaxFailures int           // how many failures to triage (default 5)
	PerCall     time.Duration // timeout per model call (default 45s)
}

const triageSystemPrompt = `You triage failed Flutter end-to-end tests written in ProbeScript.
You get the failing test name and the error. The error may name the line, the step, and the texts and keys that were visible on screen when it failed.

Answer in at most 4 short sentences:
1. The most probable cause. Say whether it looks like a test-script problem (wrong selector, text changed, timing, scroll position, a dialog still animating) or a possible app bug.
2. One concrete thing to try next.
If the information is not enough to tell, say so plainly. Never invent screens, widgets or keys that are not in the error.`

// Triage asks c for a short advisory note per failure. It is advisory output
// only and is built so it can never affect a test run:
//   - it takes already-final results (plain strings, no live state);
//   - every call is time-bounded, there are no retries, and the number of
//     failures is capped;
//   - after the first transport/provider error it stops (a dead endpoint is
//     not hammered once per failure) and reports one unavailable note;
//   - a panic inside the provider is recovered and treated like an error.
//
// It never returns an error: the second result says why triage stopped early,
// "" if it ran to completion.
func Triage(ctx context.Context, c TextCompleter, failures []Failure, opts TriageOptions) (notes []TriageNote, stopped string) {
	defer func() {
		if r := recover(); r != nil {
			stopped = fmt.Sprintf("AI provider panicked: %v", r)
		}
	}()
	if c == nil || len(failures) == 0 {
		return nil, ""
	}
	if opts.MaxFailures <= 0 {
		opts.MaxFailures = 5
	}
	if opts.PerCall <= 0 {
		opts.PerCall = 45 * time.Second
	}

	for i, f := range failures {
		if i >= opts.MaxFailures {
			stopped = fmt.Sprintf("only the first %d of %d failures were triaged", opts.MaxFailures, len(failures))
			break
		}
		callCtx, cancel := context.WithTimeout(ctx, opts.PerCall)
		out, err := c.Complete(callCtx, triageSystemPrompt, triageUserPrompt(f))
		cancel()
		if err != nil {
			return notes, fmt.Sprintf("AI triage unavailable: %v", err)
		}
		advice := ReasoningStripped(out)
		if advice == "" {
			return notes, "AI triage unavailable: the model returned an empty answer"
		}
		notes = append(notes, TriageNote{Test: f.Test, Advice: advice})
	}
	return notes, stopped
}

func triageUserPrompt(f Failure) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "Test: %s\n", f.Test)
	if f.File != "" {
		fmt.Fprintf(&sb, "File: %s\n", f.File)
	}
	// Bound the prompt: a pathological multi-KB error must not blow a small
	// model's context window.
	errText := f.Error
	if r := []rune(errText); len(r) > 3000 {
		errText = string(r[:3000]) + "…"
	}
	fmt.Fprintf(&sb, "Error:\n%s\n", errText)
	return sb.String()
}

// FormatTriageMarkdown renders notes (and why triage stopped, if it did) for
// stdout and <reports>/triage.md.
func FormatTriageMarkdown(notes []TriageNote, stopped string) string {
	var sb strings.Builder
	sb.WriteString("# AI triage (advisory)\n\n")
	sb.WriteString("_Generated by a language model from the failure text. It does not change any test result._\n\n")
	for _, n := range notes {
		fmt.Fprintf(&sb, "## %s\n\n%s\n\n", n.Test, n.Advice)
	}
	if stopped != "" {
		fmt.Fprintf(&sb, "> %s\n", stopped)
	}
	return sb.String()
}
